FROM python:3.8.3
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    mariadb-server \
    python3-dev
RUN pip install --upgrade pip
RUN pip install pipenv
COPY Pipfile /Pipfile
COPY Pipfile.lock /Pipfile.lock
RUN pipenv install --dev --system
RUN mkdir -p /src
WORKDIR /src
CMD tail -f /dev/null