FROM python:3.8.3-buster
RUN apt-get update && apt-get install -y \
    build-essential \
    python-dev \

RUN pip install --upgrade pip
RUN pip install pipenv
COPY Pipfile /Pipfile
COPY Pipfile.lock /Pipfile.lock
RUN pipenv install --dev --system
RUN mkdir -p /src
WORKDIR /src